version: "3.7"

services:
  jupyter:
    build: ./jupyter
    image: jupyter
    restart: always
    container_name: jupyter
    environment:
      - APP_NAME=jupyter
    expose:
      - 8888

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - 8000:8000